#!/bin/bash
# quick script to build the documentation and make a release

git status |grep dred
if [ "$?" == ] ; then
  echo "Cannot make a release as there are things outstanding from git"
  exit
fi

dzil install

# create the 
ct2 README.md -o docs/README.html
ct2 README.md -o docs/README.pdf

git push -u origin master
dzil release