#!/usr/bin/perl -w
# quick way to create mscgen images
#
# (c) kevin Mulholland 2013, moodfarm@cpan.org
# this code is released under the Perl Artistic License

use 5.12.0;
use strict;
use warnings;
use App::Basis;
use App::Basis::ConvertText::Graphviz;

# -----------------------------------------------------------------------------

my $text = <<EOD;
digraph GRAPH_0 {

  edge [ arrowhead=open ];
  graph [
    fontsize=22,
    style=filled,
    fontname="sans-serif",
    label="Liberator Cloud",
    labelloc=top ];
  node [
    fontsize=11,
    fillcolor=white,
    style=filled,
    shape=box ];

  subgraph "cluster0" {
  label="Group \#0";
  style=filled;
  labelloc=top;
  labeljust=l;
  fontsize="8.8";
  fontname=serif;
  fontcolor="#000000";
  fillcolor="#ffffff";
  color="#000000";
  border=none;

  }
  subgraph "cluster2" {
  label="Group \#2";
  style=filled;
  labelloc=top;
  labeljust=l;
  label="Customer Cloud";
  fontsize="8.8";
  fontname="sans-serif";
  fontcolor="#000000";
  fillcolor="#e5e5e5";
  color="#000000";

  custom_web [ fillcolor="#a6cee3", label="Web Cluster" ]
  custom_db [ fillcolor="#b2df8a", label="Database Cluster" ]
  custom_cache [ fillcolor="#fdbf6f", label="Cache Cluster" ]
  custom_svc [ fillcolor="#cab2d6", label=Services ]
  custom_dwh [ fillcolor="#fb9a99", label=Reporting ]
  }
  subgraph "cluster14" {
  label="Group \#14";
    subgraph "cluster50" {
    label="Group \#50";
    style=filled;
    labelloc=top;
    labeljust=l;
    label=Reporting;
    fontsize="8.8";
    fontname="sans-serif";
    fontcolor="#ffffff";
    fillcolor="#e31a1c";
    color="#000000";

    dwh [ fillcolor="#fb9a99", label="Data Warehouse" ]
    one [ fillcolor="#fb9a99" ]
    two [ fillcolor="#fb9a99" ]
    }
    subgraph "cluster31" {
    label="Group \#31";
    style=filled;
    labelloc=top;
    labeljust=l;
    label="Database Cluster";
    fontsize="8.8";
    fontname="sans-serif";
    fontcolor="#ffffff";
    fillcolor="#33a02c";
    color="#000000";

    db [ fillcolor="#b2df8a", label="Database Proxy" ]
    "master1" [ fillcolor="#b2df8a" ]
    "slave1" [ fillcolor="#b2df8a" ]
    "master2" [ fillcolor="#b2df8a" ]
    "slave2" [ fillcolor="#b2df8a" ]
    masterx [ fillcolor="#b2df8a" ]
    slavex [ fillcolor="#b2df8a" ]
    "static master" [ fillcolor="#b2df8a" ]
    "slave master" [ fillcolor="#b2df8a" ]
    }
    subgraph "cluster30" {
    label="Group \#30";
    style=filled;
    labelloc=top;
    labeljust=l;
    label="Cache Cluster";
    fontsize="8.8";
    fontname="sans-serif";
    fontcolor="#ffffff";
    fillcolor="#ff7f00";
    color="#000000";

    cache [ fillcolor="#fdbf6f", label=Cache ]
    }
    subgraph "cluster26" {
    label="Group \#26";
    style=filled;
    labelloc=top;
    labeljust=l;
    label=Services;
    fontsize="8.8";
    fontname="sans-serif";
    fontcolor="#ffffff";
    fillcolor="#6a3d9a";
    color="#000000";

    service [ fillcolor="#cab2d6", label="Services Data Ingest" ]
    }
    subgraph "cluster17" {
    label="Group \#17";
    style=filled;
    labelloc=top;
    labeljust=l;
    label="Web Cluster";
    fontsize="8.8";
    fontname="sans-serif";
    fontcolor="#ffffff";
    fillcolor="#1f78b4";
    color="#000000";

    "load balancers" [ fillcolor="#a6cee3", label="Load Balancers" ]
    proxy [ fillcolor="#a6cee3", label=Proxies ]
    "web srvr" [ fillcolor="#a6cee3", label="Web servers" ]
    }
  style=filled;
  labelloc=top;
  labeljust=l;
  label="Inview Cloud";
  fontsize="8.8";
  fontname="sans-serif";
  fontcolor="#000000";
  fillcolor="#ffffff";
  color="#000000";

  juicelive [ fillcolor="#ffff99", label="Juice Live" ]
  }
  juicelive -> "load balancers" [ color="#000000" ]
  juicelive -> custom_web [ color="#000000" ]
  custom_web -> custom_db [ color="#000000" ]
  custom_web -> custom_cache [ color="#000000" ]
  custom_db -> custom_dwh [ color="#000000" ]
  custom_svc -> custom_db [ color="#000000" ]
  custom_svc -> custom_cache [ color="#000000" ]
  "load balancers" -> proxy [ color="#000000" ]
  proxy -> "web srvr" [ color="#000000" ]
  "web srvr" -> db [ color="#000000" ]
  "web srvr" -> cache [ color="#000000" ]
  db -> "static master" [ color="#000000" ]
  db -> "master1" [ color="#000000" ]
  db -> dwh [ color="#000000" ]
  db -> "master2" [ color="#000000" ]
  db -> masterx [ color="#000000" ]
  service -> db [ color="#000000" ]
  service -> cache [ color="#000000" ]
  dwh -> one [ color="#000000" ]
  "master1" -> "slave1" [ color="#000000" ]
  "master2" -> "slave2" [ color="#000000" ]
  masterx -> slavex [ color="#000000" ]
  "static master" -> "slave master" [ color="#000000" ]
  one -> two [ color="#000000" ]
}

EOD

# -----------------------------------------------------------------------------
# main

my %opt = init_app(
    help_text => "Create simple charts images",
    options   => {
        # 'filename|f=s' => {
        #     desc     => 'filename to save as',
        #     required => 1,
        # },
        # 'input=s' => {
        #     desc     => 'input data csv file',
        #     required => 1,
        #     validate => sub { -f $_ },
        # },
     }
);


$opt{filename} = '/tmp/fred.png';

my $status = graphviz( $text, $opt{filename}, undef );
say "failed to create chart" if ( !$status );
